version: "3.7"

services:
  plex:
    image: plexinc/pms-docker:latest
    restart: always
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"
      TZ: "UTC"
    volumes:
      - ${APP_DATA_DIR}/data/plex/config:/config
      - ${APP_DATA_DIR}/data/plex/transcode:/transcode
      - ${APP_DATA_DIR}/data/plex/media:/data
