version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: johnsapps-open-webui-ollama_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
    
  web:
    image: ghcr.io/open-webui/open-webui:ollama@sha256:d2a1732a7befe9481bcf884bee3b848f89ca51e16e3f0d198358fa0b651159d3
    volumes:
      - ${APP_DATA_DIR}/data/open-webui-ollama/ollama:/root/.ollama
      - ${APP_DATA_DIR}/data/open-webui-ollama/open-webui:/app/backend/data
    runtime: nvidia
    restart: always
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
